# Generated by Django 5.0 on 2023-12-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_company_photo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='introdcution',
            new_name='introduction',
        ),
    ]
